#ifndef AVOCADOS_ISR_H_
#define AVOCADOS_ISR_H_

void isr_0(void);
void isr_1(void);
void isr_2(void);
void isr_3(void);
void isr_4(void);
void isr_5(void);
void isr_6(void);
void isr_7(void);
void isr_8(void);
void isr_10(void);
void isr_11(void);
void isr_12(void);
void isr_13(void);
void isr_14(void);
void isr_16(void);
void isr_17(void);
void isr_18(void);
void isr_19(void);
void isr_21(void);
void isr_32(void);
void isr_33(void);
void isr_34(void);
void isr_35(void);
void isr_36(void);
void isr_37(void);
void isr_38(void);
void isr_39(void);
void isr_40(void);
void isr_41(void);
void isr_42(void);
void isr_43(void);
void isr_44(void);
void isr_45(void);
void isr_46(void);
void isr_47(void);
void isr_48(void);
void isr_49(void);
void isr_50(void);
void isr_51(void);
void isr_52(void);
void isr_53(void);
void isr_54(void);
void isr_55(void);
void isr_56(void);
void isr_57(void);
void isr_58(void);
void isr_59(void);
void isr_60(void);
void isr_61(void);
void isr_62(void);
void isr_63(void);

#endif /* ! AVOCADOS_ISR_H_ */
